### ISSUE TITLE
Using custom built Clp binaries for v1.0.1

### ISSUE THREAD

**Issue by molet** [jump-dev/Clp.jl#136]
Hello, 

I'm wondering whether it's possible to use custom installation of Clp for `Clp.jl` version 1.0.1 just like it was possible for v0.9.1. Thanks a lot.

**Comment by odow** [comment]
See https://jump.dev/JuMP.jl/stable/developers/custom_solver_binaries/. Why do you want to do this?

**Comment by molet** [comment]
Nice - thanks a lot! There seems to be a bug in Clp version 1.17.6 (and even version 1.17.7) that gives a segfault for an appropriately large system I have and it's fixed in the current master branch of Clp (not tagged yet). I you know that versions above 1.17.6 are not necessarily supported by Clp.jl but I tried using the compiled master version within Clp.jl v0.9.1 and it worked perfectly so I assume it would work with v1.0.1 as well (at least with those options I pass).

**Comment by meetsaiya** [comment]
Hey @odow , I tried installing Sigmoidal Programming and it showed error that I have installed v1.7.1 of Clp. The git repo recommends version 0.8 of clp. Would I need to install an older version or will this work? I'm using Julia 1.8.5 with IJulia in notebook. Looking forward to your help!
