### ISSUE TITLE
Test the LAPACK fallback

### ISSUE THREAD

**Issue by mlubin** [jump-dev/Clp.jl#53]
See https://github.com/JuliaOpt/Clp.jl/pull/52#issuecomment-456619513.

**Comment by juan-pablo-vielma** [comment]
Sent an email to the Clp list asking for the best way to test it.

**Comment by mtanneau** [comment]
If it helps, that error arises when trying to solve the QAP12 from Netlib, which is "only" 1.4MB.
That instance can be downloaded here: ftp://ftp.numerical.rl.ac.uk/pub/cuter/netlib/QAP12.SIF

```julia
import Clp  # v0.6.1
import MathProgBase
MPB = MathProgBase

model = MPB.LinearQuadraticModel(Clp.ClpSolver())
MPB.loadproblem!(model, "qap12.mps")
MPB.optimize!(model)
```
raises the error
```bash
julia: symbol lookup error: /home/mathieu/.julia/packages/Clp/zGJX2/deps/usr/lib/libClp.so: undefined symbol: dgetrf_
```

**Comment by mtanneau** [comment]
Can this be closed in light of #77 ?

If it helps, I tried the `qap12` example locally with `Clp.jl#master` and did not encounter any issue.

**Comment by odow** [comment]
I believe the underlying issue is fixed, but there isn't a test.

**Comment by odow** [comment]
I still don't know a good way to test this, but it obviously hasn't been an issue since 2019. Our binary release process is not much better. We can revisit it someone hits the same issue in future.
